import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "./components/ThemeProvider";
import ThemeInitializer from './components/ThemeInitializer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="h-full">
        <ThemeInitializer />
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}


